version: "3"
services:
    test:
        image: "node:10"
        user: node
        environment:
            - NODE_ENV=test
        volumes:
            - ./:/dataframe-js
        working_dir: /dataframe-js
        command: npm run test:watch
